site_name: async Bakalari API v3
site_url: https://async-bakalari-api.schizza.cz
repo_url: https://github.com/schizza/async-bakalari-api3
repo_name: schizza/async-bakalari-api3
theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.footer
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Tmavý režim

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Světlý režim
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      # custom_fences:
      #   - name: '*'
      #     class: '*'
      #     format: !!python/name:custom_prefix.formatter
      #     validator: !!python/name:custom_prefix.validator
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: schizza/async-bakalari-api3
      branch: docs
  - search
  - git-authors

nav:
  - Úvod:
      - index.md
      - Podrobná instalace: podrobna_instalace.md

  - Bakaláři:
      - bakalari/index.md
      - Seznam škol: bakalari/seznam_skol.md
      - První přihlášení: bakalari/first_login.md
      - Tokeny: bakalari/credentials.md
      - Třída Schools: bakalari/schools.md
  - Komens:
      - komens/index.md
      - Čtení zpráv: komens/cteni_zprav.md
      - Stažení přílohy: komens/stazeni_prilohy.md
  - Marks:
      - marks/index.md
      - Přehled API: marks/api.md
  - CLI:
      - cli/index.md
      - Seznam škol: cli/seznam_skol.md
      - Přihlášení (tokeny): cli/tokeny.md
      - Zprávy: cli/komens.md
